{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yyc3-catering-platform.fullname" . }}-api-gateway
  labels:
    {{- include "yyc3-catering-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway

spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "yyc3-catering-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
